from ollama import Client
from loguru import logger
from typing import Tuple
import os
from dotenv import load_dotenv

load_dotenv()

LLM_MODEL_NAME = os.getenv('LLM_MODEL_NAME')
class OllamaGenerator:
    """
    Handles interactions with models running on Ollama.
    """
    def __init__(self, model_name: str = LLM_MODEL_NAME): # type: ignore
        self.model_name = model_name
        self.client = Client(host='http://127.0.0.1:11434')

    def generate(self, question: str, schema_info: dict) -> Tuple[str, str]:
        """
        Generates SQL and an explanation using Ollama.
        """
        # Convert schema dict to string
        schema_parts = []
        for table, cols in schema_info.items():
            col_strings = []
            for c in cols:
                info = f"{c['name']} ({c['type']})"
                if c.get('pk'): 
                    info += " PRIMARY KEY"
                col_strings.append(info)
            schema_parts.append(f"Table {table} ({', '.join(col_strings)})")
        schema_context = "\n".join(schema_parts)

        system_prompt = (
            "You are a SQL expert. Given a schema and a question, return a valid SQL query "
            "and a very brief explanation of what the query does. "
            "Your response MUST be in the following format:\n"
            "SQL: <your_sql>\n"
            "EXPLANATION: <your_brief_explanation>"
        )
        
        user_prompt = f"Schema:\n{schema_context}\n\nQuestion: {question}"

        try:
            logger.info(f"Ollama: Sending request to {self.model_name} at 127.0.0.1:11434")
            response = self.client.chat(model=self.model_name, messages=[
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_prompt},
            ])
            
            content = response['message']['content']
            logger.info("Ollama: Received response")
            
            sql = ""
            explanation = ""
            if "SQL:" in content and "EXPLANATION:" in content:
                parts = content.split("EXPLANATION:")
                sql = parts[0].replace("SQL:", "").strip()
                explanation = parts[1].strip()
            else:
                sql = content.strip()
                explanation = "Generated by Ollama."

            sql = sql.replace("```sql", "").replace("```", "").strip()
            return sql, explanation

        except Exception as e:
            logger.error(f"Ollama Error: {e}")
            return f"-- Connection Error: {e}", "Could not connect to Ollama server."

def generate_with_ollama(question: str, schema_info: dict, model_name: str = LLM_MODEL_NAME): # type: ignore
    """Wrapper for Ollama generation."""
    gen = OllamaGenerator(model_name)
    return gen.generate(question, schema_info)
